---

- name: Get Database SID
  set_fact:
     database_sid: "{{ database_primary_sid | default(database_standby_sid) }}"

# If autotask_windows is not configured for this environment then simply keep the default autotask windows
- name: Set Autotask Windows
  include: set_autotask_windows.yml
  when: autotask_windows is defined
  tags: windows

# If database_autotasks is not configured for this environment then simply keep the default autotask clients
- name: Set Autotask Status
  include: set_autotask_status.yml
  when: database_autotasks is defined
  tags: status

